apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: capstone-cluster
  region: us-east-1

iam:
  withOIDC: true
nodeGroups:
  - name: ng-1
    instanceType: t2.small
    desiredCapacity: 2
    volumeSize: 80
    ssh:
      allow: true
      publicKeyName: udapeople
  - name: ng-2
    instanceType: t2.small
    desiredCapacity: 2
    volumeSize: 80
    ssh:
      allow: true
      publicKeyName: udapeople
