apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: capstone-cluster
  region: us-east-1

iam:
  withOIDC: true
  serviceRoleARN: arn:aws:iam::407769180624:user/deploy-user
nodeGroups:
  - name: ng-1
    instanceType: t2.small
    desiredCapacity: 2
    volumeSize: 10
    ssh:
      allow: true 
  - name: ng-2
    instanceType: t2.small
    desiredCapacity: 2
    volumeSize: 10
    ssh:
      publicKeyName: udapeople

