version: 2.1

jobs:
  init:
    docker:
      - image: python:3.7.3-stretch
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
      - run:
          name: Install dependencies
          command: |
            python3 -m venv .devops-capstone
            source .devops-capstone/bin/activate
            make install
      - save_cache:
          paths:
            - ./.devops-capstone/bin
          key: v1-dependencies-{{ checksum "requirements.txt" }}
      - run:
          name: Run lint
          command: |
            source .devops-capstone/bin/activate
            make lint
  deploy-docker:
    docker:
      - image: cimg/python:3.10.4
    steps:
      - checkout
      - setup_remote_docker
      - restore_cache:
          keys:
            - v1-dependencies
      - run:
          name: Deploy by makefile
          command: |
            python3 -m venv .devops-capstone
            source .devops-capstone/bin/activate
            make build-docker-v1
            make upload-docker
      - save_cache:
          paths:
            - ./.devops-capstone/bin
          key: v1-dependencies-{{ checksum "requirements.txt" }}
  create-resource:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies
      - run:
          name: install dependency
          command: |
            yum update -y
            yum groupinstall -y 'Development Tools'
            yum install -y python3
            yum upgrade
            python3 -m venv .devops-capstone
            source .devops-capstone/bin/activate
            make install
      - run:
          name: create eks
          command: |
            source .devops-capstone/bin/activate
            make eks-create-cluster
      - save_cache:
          paths:
            - ./.devops-capstone/bin
          key: v1-dependencies-{{ checksum "requirements.txt" }}
  deploy-eks:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies
      - run:
          name: install dependency
          command: |
            yum update -y
            yum groupinstall -y 'Development Tools'
            yum install -y python3
            yum upgrade
            python3 -m venv .devops-capstone
            source .devops-capstone/bin/activate
            make install
      - run:
          name: deploy eks
          command: |
            make cluster-deployment
      - save_cache:
          paths:
            - ./.devops-capstone/bin
          key: v1-dependencies-{{ checksum "requirements.txt" }}
  deploy-docker-rolling-update:
    docker:
      - image: cimg/python:3.10.4
    steps:
      - checkout
      - setup_remote_docker
      - restore_cache:
          keys:
            - v1-dependencies
      - run:
          name: Deploy by makefile
          command: |
            python3 -m venv .devops-capstone
            source .devops-capstone/bin/activate
            make build-docker-v2
            make upload-docker
      - save_cache:
          paths:
            - ./.devops-capstone/bin
          key: v1-dependencies-{{ checksum "requirements.txt" }}
  rolling-update:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies
      - run:
          name: Install tar utility
          command: |
            yum install -y tar gzip
            make install

      - run:
          name: update
          no_output_timeout: 60m
          command: |
            yum update -y
            yum groupinstall -y 'Development Tools'
            yum install -y python3
            yum upgrade
            python3 -m venv .devops-capstone
            source .devops-capstone/bin/activate
            aws configure set aws_access_key_id AKIAV54HP5HILPQVAXZX
            aws configure set aws_secret_access_key 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
            aws configure set region us-east-1
            aws sts get-caller-identity
            make rollout-status

  clean-up:
    docker:
      - image: python:3.7.3-stretch
    steps:
      - checkout
      - run:
          name: Delete resource
          command: |
            make cluster-cleanup
            make eks-delete-cluster

workflows:
  default:
    jobs:
      - init
      - deploy-docker:
          requires: [init]
      - create-resource:
          requires: [deploy-docker]
      - deploy-eks:
          requires: [create-resource]
      - deploy-docker-rolling-update:
          requires: [deploy-eks]
      - rolling-update:
          requires: [deploy-docker-rolling-update]
      - clean-up:
          requires: [rolling-update]
