version: 2.1

orbs:
  docker: circleci/docker@1.5.0

jobs:
  init:
    docker:
      - image: python:3.7.3-stretch
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "hello_app/requirements.txt" }}
            # fallback to using the latest cache if no exact match is found
            # - v1-dependencies-
      - run:
          name: Install dependencies
          command: |
            python3 -m venv .devops-capstone
            source .devops-capstone/bin/activate
            make install
      - save_cache:
          paths:
            - ./.devops-capstone/bin/activate # TODO: Include in cache the "bin" directory
          key: v1-dependencies-{{ checksum "hello_app/requirements.txt" }}
      - run:
          name: Run lint
          command: |
            source .devops-capstone/bin/activate
            make lint
  deploy-docker:
    docker:
      - image: cimg/python:3.10.4
    steps:
      - checkout
      - setup_remote_docker
      - restore_cache:
          keys:
            - v1-dependencies
      - run:
          name: Deploy by makefile
          command: |
            source activate
            make build-docker
            make upload-docker
  create-resource:
    docker:
      - image: python:3.7.3-stretch
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies
      - run:
          name: create eks and start minikube
          command: |
            source activate
            make eks-create-cluster
            minikube start
  deploy-eks:
    docker:
      - image: python:3.7.3-stretch
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies
      - run:
          name: deploy eks
          command: |
            make k8s-deployment
            make port-forwarding
  rolling-update:
    docker:
      - image: python:3.7.3-stretch
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies
      - run:
          name: Install tar utility
          command: |
            yum install -y tar gzip

      - run:
          name: update
          no_output_timeout: 30m
          command: |
            source .devops-capstone/bin/activate
            make rolling-update

  clean-up:
    docker:
      - image: python:3.7.3-stretch
    steps:
      - checkout  
      - run:
          name: Delete resource
          command: |
            make k8s-cleanup-resource
            make eks-delete-cluster

workflows:
  default:
    jobs:
      - init
      - deploy-docker: 
          requires: [init]
      - create-resource:
          requires: [deploy-docker]
      - deploy-eks:
          requires: [create-resource]
      - rolling-update:
          requires: [deploy-eks]
      - clean-up:
          requires: [rolling-update]
